FROM ubuntu:16.04

MAINTAINER Jakub Bednar <https://github.com/bednar>

# this is a non-interactive automated build - avoid some warning messages
ENV DEBIAN_FRONTEND noninteractive

# update dpkg repositories
RUN apt-get update --fix-missing

# install wget, unzip, sudo
RUN apt-get install -y wget unzip sudo apt-transport-https

# add Elastic.co repository
RUN wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
RUN echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-5.x.list
RUN apt-get update

# Recipes

${recipes}

# remove download archive files
RUN apt-get clean

# expose ports
EXPOSE ${exposePorts}

# Create Log files
RUN touch ${logFiles}
RUN chmod a+w ${logFiles}

# Start services & show logs
CMD ["sh", "-c", "for s in ${services}; do service \$s start; done && tail -f ${logFiles}"]