version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install the Groovy
          command: apt-get update && apt-get install -y groovy
      - run:
          name: Build the Dockerfile
          command: echo Hello, world.
      - run:
          name: Build the Docker image
          command: docker build -t bednar/docker-spring-micro-services:$CIRCLE_BRANCH .