version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install the Groovy
          command: sudo apt-get update && sudo apt-get install -y groovy
      - run:
          name: Build the Dockerfile
          command: groovy --version
      - run:
          name: Build the Docker image
          command: docker build -t bednar/docker-spring-micro-services:$CIRCLE_BRANCH .