version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install the Groovy
          command: sudo apt-get update && sudo apt-get install -y groovy
      - run:
          name: Build the Dockerfile
          command: groovy build.groovy
      - run:
          name: Build the Docker image
          command: docker build -t bednar/docker-spring-micro-services:$CIRCLE_BRANCH .
      - run:
          name: Trigger automated build at https://hub.docker.com
          command: chmod +x ./scripts/release.sh && ./scripts/release.sh