version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install the Groovy
          command: sudo apt-get update && sudo apt-get install -y groovy
      - run:
          name: Build the Dockerfile
          command: groovy build.groovy
      - run:
          name: Build the Docker image
          command: docker build -t bednar/docker-spring-micro-services:$CIRCLE_BRANCH .
      - deploy:
          name: Trigger automated build at https://hub.docker.com
          command: |
            if [[ "${CIRCLE_BRANCH}" =~ ^[0-9.]+$ ]]
            then
              echo The Dockerfile, for branch \'${CIRCLE_BRANCH}\', will be push to the repository.
              git config --global user.name "CircleCI"
              git config --global user.email "sezeyetev@hitbts.comm"
              git remote show origin
              git status
              echo add Dockerfile
              git add Dockerfile -f
              git status
              echo commit
              git commit -m '[ci skip]'
              git status
              echo push
              git push --set-upstream origin ${CIRCLE_BRANCH}
              git status
            else
              echo The branch name \'${CIRCLE_BRANCH}\' does not match regexp \'\^[0-9.]+\$\' =\> Dockerfile is not push to the repository.
            fi