#!/bin/bash

echo "Waiting for the Elasticsearch start..."

while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' 0.0.0.0:9200)" == "000" ]]; do
    printf '...'
    sleep 5
done

echo "done"

curl -XPUT '0.0.0.0:9200/micro-provisioning?pretty&pretty'
curl -XPUT '0.0.0.0:9200/micro-provisioning/doc/1?pretty&pretty' -H 'Content-Type: application/json' -d'
{
  "name": "Sample Data"
}
'