#!/bin/bash
#
#
# Thx https://github.com/elastic/kibana/issues/3709#issuecomment-347582983
#
#

while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' 0.0.0.0:5601)" == "000" ]]; do
    printf '...'
    sleep 5
done

# Wait for finish indexing by ElasticSearch
sleep 15

KIBANA_URL="http://0.0.0.0:5601"
INDEX_PATTERN="micro-*"
time_field="@timestamp"

# Create index pattern and get the created id
# curl -f to fail on error
KIBANA_INDEX_ID=$(curl -f -XPOST -H "Content-Type: application/json" -H "kbn-xsrf: anything" \
  "$KIBANA_URL/api/saved_objects/index-pattern" \
  -d"{\"attributes\":{\"title\":\"$INDEX_PATTERN\",\"timeFieldName\":\"$time_field\"}}" \
  | jq -r '.id')

# Create the default index
curl -XPOST -H "Content-Type: application/json" -H "kbn-xsrf: anything" \
  "$KIBANA_URL/api/kibana/settings/defaultIndex" \
  -d"{\"value\":\"$KIBANA_INDEX_ID\"}"